Repository DjangoGirls/tutorial, pull requests merged in 2019-09, with the labels that each got.

#1292 Use fork of sectionx plugin to fix arrow direction
  book.json
Labels: type: gitbook

#1563 fix: rename lottery to polish equivalent
  pl/python_introduction/README.md
Labels: type: translations

#1452 Update README.md
  ru/extend_your_application/README.md
Labels: type: translations

#1453 deleted blog.views. from def post_new(requests)
  es/django_forms/README.md
Labels: type: translations

#1239 sk/intro_to_command_line - fix exit command int overview table
  sk/intro_to_command_line/README.md
Labels: type: translations

#1240 sk/python_introduction - fix lottery variable name
  sk/python_introduction/README.md
Labels: type: translations

#1467 fix:Change some example code of django_models.md because of upgrade Python version
  ko/README.md
  ko/django_models/README.md
Labels: type: translations

#1417 Control + break for windows
  en/django_urls/README.md
Labels: status: needs action from author

#1432 Fix issues on the Spanish translation
  es/deploy/README.md
  es/django_templates/README.md
  es/dynamic_data_in_templates/README.md
  es/intro_to_command_line/README.md
  es/python_introduction/README.md
Labels: type: translations

#1558 Typo correction in Korean "Deploy!" chapter: "삭제되도" → "삭제돼도"
  ko/deploy/README.md
Labels: status: needs review, type: translations

#1571 master: Fix es typos
  es/django_forms/README.md
  es/django_orm/README.md
  es/django_start_project/README.md
  es/django_urls/README.md
  es/django_views/README.md
  es/whats_next/README.md
Labels: type: translations

#1533 Fix typo in Chinese translation
  zh/django_views/README.md
Labels: type: translations

#1573 German translation improvements from Crowdin made by:
  de/SUMMARY.md
  de/chromebook_setup/instructions.md
  de/deploy/README.md
  de/django_admin/README.md
  de/django_forms/README.md
  de/django_models/README.md
  de/django_start_project/README.md
  de/django_urls/README.md
  de/django_views/README.md
  de/dynamic_data_in_templates/README.md
  de/extend_your_application/README.md
  de/intro_to_command_line/README.md
  de/python_installation/instructions.md
  de/whats_next/README.md
Labels: type: translations

#1540 Spanish translation improvements from Crowdin made by:
  es/README.md
  es/SUMMARY.md
  es/chromebook_setup/instructions.md
  es/code_editor/README.md
  es/code_editor/instructions.md
  es/css/README.md
  es/deploy/README.md
  es/deploy/install_git.md
  es/deploy/signup_pythonanywhere.md
  es/django_admin/README.md
  es/django_forms/README.md
  es/django_installation/instructions.md
  es/django_models/README.md
  es/django_orm/README.md
  es/django_start_project/README.md
  es/django_templates/README.md
  es/django_urls/README.md
  es/django_views/README.md
  es/dynamic_data_in_templates/README.md
  es/extend_your_application/README.md
  es/how_the_internet_works/README.md
  es/html/README.md
  es/installation/README.md
  es/intro_to_command_line/README.md
  es/intro_to_command_line/open_instructions.md
  es/python_installation/instructions.md
  es/python_introduction/README.md
  es/template_extending/README.md
  es/whats_next/README.md
Labels: type: translations

#1574 Japanese translation improvements from Crowdin made by:
  ja/SUMMARY.md
  ja/chromebook_setup/instructions.md
  ja/code_editor/README.md
  ja/code_editor/instructions.md
  ja/css/README.md
  ja/deploy/README.md
  ja/deploy/install_git.md
  ja/deploy/signup_pythonanywhere.md
  ja/django_admin/README.md
  ja/django_forms/README.md
  ja/django_installation/instructions.md
  ja/django_models/README.md
  ja/django_orm/README.md
  ja/django_start_project/README.md
  ja/django_templates/README.md
  ja/django_urls/README.md
  ja/django_views/README.md
  ja/dynamic_data_in_templates/README.md
  ja/extend_your_application/README.md
  ja/how_the_internet_works/README.md
  ja/html/README.md
  ja/installation/README.md
  ja/intro_to_command_line/README.md
  ja/intro_to_command_line/open_instructions.md
  ja/python_installation/instructions.md
  ja/python_introduction/README.md
  ja/template_extending/README.md
  ja/whats_next/README.md
Labels: type: translations
